apiVersion: apps/v1
kind: Deployment
metadata:
  name: lrucachestore-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lrucachestore-backend
  template:
    metadata:
      labels:
        app: lrucachestore-backend
    spec:
      containers:
        - name: lrucachestore-backend 
          image: 14081995/lrucachestorebackend:1.0.2
          ports:
            - containerPort: 8080
